runtime: nodejs14

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico
  - url: /static
    static_dir: public
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto