apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontendcluster
  name: frontendcluster
  namespace: default
spec:
  selector:
    matchLabels:
      app: frontendcluster
  template:
    metadata:
      labels:
        app: frontendcluster
    spec:
      containers:
      - image: gcr.io/akkofinder/frontendcluster:1.0
        imagePullPolicy: Always
        name: frontendcluster
        ports:
          - containerPort: 3000
            protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontendcluster
  name: frontendcluster
  namespace: default
spec:
  ports:
  - nodePort: 30955
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: frontendcluster
  type: LoadBalancer

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontendcluster
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontendcluster
  targetCPUUtilizationPercentage: 10
