runtime: nodejs14
env: standard
service: backend
env_variables:
  MONGO_URI: "mongodb+srv://todo:rG4x90JGGtZKNlKs@cluster0.q6ukq.mongodb.net/db?retryWrites=true&w=majority"
  JWT_KEY: "secret"
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
