runtime: nodejs14
env: standard
env_variables:
  MONGO_URI: $MONGO_URI
  JWT_KEY: $JWT_KEY
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
