name: Deploy frontend to Google App Engine
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    name: Deploying to Google Cloud Platform
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Install Client
      run: NPM_CONFIG_PRODUCTION=false npm install --prefix client
      env:
        CI: false

    - name: Build Client
      run: NPM_CONFIG_PRODUCTION=false npm run build --prefix client
      env:
        CI: false

    - name: Deploy to Google App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: ./client/app.yaml
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}
